workspace:
  base: /go
  path: src/github.com/evelynocean/coconut

kind: pipeline
type: docker
name: backend

steps:
- name: golang_test
  image: golang:1.16
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on
  commands:
    - go get -u --insecure ./...
    - go mod vendor
    - cd lib/error
    - go test -cover
    - cd ../lib
    - go test -cover

- name: golangci-lint
  image: golangci/golangci-lint:v1.42.1-alpine
  commands:
    - golangci-lint run
