workspace:
  base: /go
  path: src/github.com/evelynocean/coconut

kind: pipeline
type: docker
name: backend

steps:
- name: golang_test
  image: golang:1.14.8-alpine3.11
  commands:
    - go test -mod=vendor -cover

- name: golangci-lint
  image: gcr.io/rd2-test/golangci-lint:latest
  commands:
    - golangci-lint run
- name: build
  image: golang:latest
  commands:
    - go build -a -mod vendor