workspace:
  base: /go
  path: src/github.com/evelynocean/coconut

pipeline:
  golang_test:
    image: golang:1.14.8-alpine3.11
    commands:
      - go vet
      - go test -v -cover
  golangci-lint:
    image: gcr.io/rd2-test/golangci-lint:latest
    commands:
      - golangci-lint run
  build:
    image: golang:latest
    commands:
      - go build -a -mod vendor